// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moodifyApi.MoodifyContext;

#nullable disable

namespace moodifyApi.Migrations
{
    [DbContext(typeof(MoodifyDbContext))]
    [Migration("20250511000537_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("HumorMusica", b =>
                {
                    b.Property<int>("HumoresHumorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicasMusicaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HumoresHumorId", "MusicasMusicaId");

                    b.HasIndex("MusicasMusicaId");

                    b.ToTable("HumorMusica");
                });

            modelBuilder.Entity("HumorUsuario", b =>
                {
                    b.Property<int>("HumoresAtuaisHumorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuariosUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HumoresAtuaisHumorId", "UsuariosUsuarioId");

                    b.HasIndex("UsuariosUsuarioId");

                    b.ToTable("HumorUsuario");
                });

            modelBuilder.Entity("MusicaPlaylist", b =>
                {
                    b.Property<int>("MusicasMusicaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistsPlaylistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MusicasMusicaId", "PlaylistsPlaylistId");

                    b.HasIndex("PlaylistsPlaylistId");

                    b.ToTable("MusicaPlaylist");
                });

            modelBuilder.Entity("moodifyApi.Models.Humor", b =>
                {
                    b.Property<int>("HumorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HumorId");

                    b.ToTable("Humores");
                });

            modelBuilder.Entity("moodifyApi.Models.Musica", b =>
                {
                    b.Property<int>("MusicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusicaId");

                    b.ToTable("Musicas");
                });

            modelBuilder.Entity("moodifyApi.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("moodifyApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HumorMusica", b =>
                {
                    b.HasOne("moodifyApi.Models.Humor", null)
                        .WithMany()
                        .HasForeignKey("HumoresHumorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moodifyApi.Models.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasMusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumorUsuario", b =>
                {
                    b.HasOne("moodifyApi.Models.Humor", null)
                        .WithMany()
                        .HasForeignKey("HumoresAtuaisHumorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moodifyApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicaPlaylist", b =>
                {
                    b.HasOne("moodifyApi.Models.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasMusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moodifyApi.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsPlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("moodifyApi.Models.Playlist", b =>
                {
                    b.HasOne("moodifyApi.Models.Usuario", "Usuario")
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("moodifyApi.Models.Usuario", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
